SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[vwDailyUpdSlct_DailyFlash_05]
AS
SELECT DailyFlash04.[date], 
       DailyFlash04.[fiscal wk], 
       DailyFlash04.[fiscal month #], 
       DailyFlash04.[fiscal month], 
       DailyFlash04.[fiscal qtr], 
       DailyFlash04.[fiscal year], 
       DailyFlash04.[status], 
       DailyFlash04.[demand units], 
       DailyFlash04.[demand cost $], 
       DailyFlash04.[demand $], 
       DailyFlash04.[advertised demand $], 
       DailyFlash04.[demand margin $], 
       DailyFlash04.[demand margin %], 
       DailyFlash04.[demand aur], 
       DailyFlash04.[demand auc], 
       DailyFlash04.[tax $], 
       DailyFlash04.[cancel units], 
       DailyFlash04.[cancel cost $], 
       DailyFlash04.[cancel $], 
       DailyFlash04.[advertised cancel $], 
       DailyFlash04.[cancel margin $], 
       DailyFlash04.[cancel margin %], 
       DailyFlash04.[shipped units], 
       DailyFlash04.[shipped cost $], 
       DailyFlash04.[shipped $], 
       DailyFlash04.[advertised shipped $], 
       DailyFlash04.[shipped margin $], 
       DailyFlash04.[shipped margin %], 
       DailyFlash04.[shipped aur], 
       DailyFlash04.[shipped auc], 
       Sum(dailyrtn.rtn_units)    AS [Return Units], 
       Sum(dailyrtn.[rtn_cost$])  AS [Return Cost $], 
       Sum(dailyrtn.[rtn_net$])   AS [Return $], 
       Sum(dailyrtn.[rtn_gross$]) AS [Advertised Return $], 
       DailyFlash04.[exchange units], 
       DailyFlash04.[exchange cost $], 
       DailyFlash04.[exchange $], 
       DailyFlash04.[advertised exchange $] 
FROM   dbo.vwDailyUpdSlct_DailyFlash_04 AS DailyFlash04
       LEFT JOIN dbo.mktbl_dailyrtn AS dailyrtn 
              ON ( DailyFlash04.[status] = dailyrtn.[status] ) 
                 AND ( DailyFlash04.[date] = dailyrtn.[rtn_date] ) 
GROUP  BY DailyFlash04.[date], 
          DailyFlash04.[fiscal wk], 
          DailyFlash04.[fiscal month #], 
          DailyFlash04.[fiscal month], 
          DailyFlash04.[fiscal qtr], 
          DailyFlash04.[fiscal year], 
          DailyFlash04.[status], 
          DailyFlash04.[demand units], 
          DailyFlash04.[demand cost $], 
          DailyFlash04.[demand $], 
          DailyFlash04.[advertised demand $], 
          DailyFlash04.[demand margin $], 
          DailyFlash04.[demand margin %], 
          DailyFlash04.[demand aur], 
          DailyFlash04.[demand auc], 
          DailyFlash04.[tax $], 
          DailyFlash04.[cancel units], 
          DailyFlash04.[cancel cost $], 
          DailyFlash04.[cancel $], 
          DailyFlash04.[advertised cancel $], 
          DailyFlash04.[cancel margin $], 
          DailyFlash04.[cancel margin %], 
          DailyFlash04.[shipped units], 
          DailyFlash04.[shipped cost $], 
          DailyFlash04.[shipped $], 
          DailyFlash04.[advertised shipped $], 
          DailyFlash04.[shipped margin $], 
          DailyFlash04.[shipped margin %], 
          DailyFlash04.[shipped aur], 
          DailyFlash04.[shipped auc], 
          DailyFlash04.[exchange units], 
          DailyFlash04.[exchange cost $], 
          DailyFlash04.[exchange $], 
          DailyFlash04.[advertised exchange $]; 
GO
