SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
Create view  [dbo].[VWSlct_OrderFlow_03]
As
SELECT OrderFlow02.[Order #], OrderFlow02.[Internet Order #], OrderFlow02.Channel, OrderFlow02.[Customer #], OrderFlow02.[Order Date], OrderFlow02.[Item Date], IIf(Left([event #],1)='2','Clearance','Full Price') AS Status, OrderFlow02.[Event #], OrderFlow02.[Demand Units], OrderFlow02.[Demand Cost $], OrderFlow02.[Demand $], OrderFlow02.[Advertised Demand $], OrderFlow02.[Tax $], OrderFlow02.INV10, OrderFlow02.Line, OrderFlow02.[Ordered Fiscal Wk], OrderFlow02.[Ordered Fiscal Month #], OrderFlow02.[Ordered Fiscal Month], OrderFlow02.[Ordered Fiscal Qtr], OrderFlow02.[Ordered Fiscal Year], OrderFlow02.[Immediate Cancel Units], OrderFlow02.[Immediate Cancel Cost $], OrderFlow02.[Immediate Cancel $], OrderFlow02.[Advertised Immediate Cancel $], OrderFlow02.[Immediate Cancel Date], OrderFlow02.[Immediate Cancel Fiscal Wk], OrderFlow02.[Immediate Cancel Fiscal Month #], OrderFlow02.[Immediate Cancel Fiscal Month], OrderFlow02.[Immediate Cancel Fiscal Qtr], OrderFlow02.[Immediate Cancel Fiscal Year], DailyCxl.Cxl_Date AS [Cancel Date], DailyCxl.Cxl_Units AS [Cancel Units], DailyCxl.[Cxl_Cost$] AS [Cancel Cost $], DailyCxl.[Cxl_Net$] AS [Cancel $], DailyCxl.[Cxl_Gross$] AS [Advertised Cancel $], DailyCxl.Cxl_RsnCd AS [Cancel RsnCd], DailyCxl.Cxl_RsnDesc AS [Cancel Rsn], DailyCxl.Cxl_Fiscal_Wk AS [Cancel Fiscal Wk], DailyCxl.[Cxl_Fiscal_Month#] AS [Cancel Fiscal Month #], DailyCxl.Cxl_Fiscal_Month AS [Cancel Fiscal Month], DailyCxl.Cxl_Fiscal_Qtr AS [Cancel Fiscal Qtr], DailyCxl.Cxl_Fiscal_Year AS [Cancel Fiscal Year], OrderFlow02.[Ship Date], OrderFlow02.[Shipped Units], OrderFlow02.[Shipped Cost $], OrderFlow02.[Shipped $], OrderFlow02.[Advertised Shipped $], OrderFlow02.[Shipped Fiscal Wk], OrderFlow02.[Shipped Fiscal Month #], OrderFlow02.[Shipped Fiscal Month], OrderFlow02.[Shipped Fiscal Qtr], OrderFlow02.[Shipped Fiscal Year]
FROM VWSlct_OrderFlow_02 as OrderFlow02 LEFT JOIN dbo.MkTbl_DailyCxl as DailyCxl  ON (OrderFlow02.Line = DailyCxl.DSeq) AND (OrderFlow02.INV10 = DailyCxl.INV10) AND (OrderFlow02.[Order #] = DailyCxl.[Order#]);
GO
