SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE view  [dbo].[VWSlct_OrderFlow_08]
as
SELECT OrderFlow07.[category], 
       OrderFlow07.[division], 
       OrderFlow07.[department], 
       OrderFlow07.[class], 
       OrderFlow07.[style], 
       OrderFlow07.[color], 
       OrderFlow07.[size], 
       OrderFlow07.[inv5], 
       OrderFlow07.[inv7], 
       OrderFlow07.[inv10], 
       OrderFlow07.[vendor #], 
       OrderFlow07.[vendor], 
       OrderFlow07.[vendor style], 
       OrderFlow07.[original price], 
       OrderFlow07.[current price], 
       OrderFlow07.[current cost], 
       OrderFlow07.[current event #], 
       OrderFlow07.[current event], 
       OrderFlow07.[last event #], 
       OrderFlow07.[last event], 
       OrderFlow07.[first sales date], 
       OrderFlow07.[first receipt date], 
       OrderFlow07.[last receipt date], 
       OrderFlow07.[next receipt date], 
       OrderFlow07.[current oh units], 
       OrderFlow07.[current oo units], 
       OrderFlow07.[next 30 days oo units], 
       OrderFlow07.[current backorder units], 
       OrderFlow07.[current backorder cost $], 
       OrderFlow07.[current backorder $], 
       OrderFlow07.[return %], 
       OrderFlow07.[order #], 
       OrderFlow07.[internet order #], 
       OrderFlow07.[line], 
       OrderFlow07.[channel], 
       OrderFlow07.[customer #], 
       OrderFlow07.[order date], 
       OrderFlow07.[item date], 
       OrderFlow07.[status], 
       OrderFlow07.[event #], 
       OrderFlow07.[event], 
       OrderFlow07.[demand units], 
       OrderFlow07.[demand cost $], 
       OrderFlow07.[demand $], 
       OrderFlow07.[advertised demand $], 
       OrderFlow07.[tax $], 
       OrderFlow07.[ordered fiscal wk], 
       OrderFlow07.[ordered fiscal month #], 
       OrderFlow07.[ordered fiscal month], 
       OrderFlow07.[ordered fiscal qtr], 
       OrderFlow07.[ordered fiscal year], 
       OrderFlow07.[immediate cancel units], 
       OrderFlow07.[immediate cancel cost $], 
       OrderFlow07.[immediate cancel $], 
       OrderFlow07.[advertised immediate cancel $], 
       OrderFlow07.[immediate cancel date], 
       OrderFlow07.[immediate cancel fiscal wk], 
       OrderFlow07.[immediate cancel fiscal month #], 
       OrderFlow07.[immediate cancel fiscal month], 
       OrderFlow07.[immediate cancel fiscal qtr], 
       OrderFlow07.[immediate cancel fiscal year], 
       OrderFlow07.[cancel date], 
       OrderFlow07.[cancel units], 
       OrderFlow07.[cancel cost $], 
       OrderFlow07.[cancel $], 
       OrderFlow07.[advertised cancel $], 
       OrderFlow07.[cancel rsncd], 
       OrderFlow07.[cancel rsn], 
       OrderFlow07.[cancel fiscal wk], 
       OrderFlow07.[cancel fiscal month #], 
       OrderFlow07.[cancel fiscal month], 
       OrderFlow07.[cancel fiscal qtr], 
       OrderFlow07.[cancel fiscal year], 
       OrderFlow07.[ship date], 
       OrderFlow07.[shipped units], 
       OrderFlow07.[shipped cost $], 
       OrderFlow07.[shipped $], 
       OrderFlow07.[advertised shipped $], 
       OrderFlow07.[shipped fiscal wk], 
       OrderFlow07.[shipped fiscal month #], 
       OrderFlow07.[shipped fiscal month], 
       OrderFlow07.[shipped fiscal qtr], 
       OrderFlow07.[shipped fiscal year], 
       OrderFlow07.[return date], 
       OrderFlow07.[return units], 
       OrderFlow07.[return cost $], 
       OrderFlow07.[return $], 
       OrderFlow07.[advertised return $], 
      ReturnCode.[reason]       AS [Return Reason], 
       ReturnCode.[grouping]     AS [Return Reason Group], 
       OrderFlow07.[return rsn] AS [Return Reason Description], 
       OrderFlow07.[return rsncd], 
       OrderFlow07.[return fiscal wk], 
       OrderFlow07.[return fiscal month #], 
       OrderFlow07.[return fiscal month], 
       OrderFlow07.[return fiscal qtr], 
       OrderFlow07.[return fiscal year], 
       OrderFlow07.[exchange date], 
       OrderFlow07.[exchange units], 
       OrderFlow07.[exchange cost $], 
       OrderFlow07.[exchange $], 
       OrderFlow07.[advertised exchange $], 
       OrderFlow07.[exchange rsncd], 
       OrderFlow07.[exchange reason], 
       OrderFlow07.[exchange fiscal wk], 
       OrderFlow07.[exchange fiscal month #], 
       OrderFlow07.[exchange fiscal month], 
       OrderFlow07.[exchange fiscal qtr], 
       OrderFlow07.[exchange fiscal year] 
FROM   [dbo].[VWSlct_orderflow_07] AS OrderFlow07
       LEFT JOIN [dbo].[reftbl_returnscode] AS ReturnCode 
              ON OrderFlow07.[return rsncd] = 
                 ReturnCode.[retcodetxt]; 
GO
