SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[vwDailyUpdSlct_DailyFlash_04]
AS
SELECT DailyFlash03.[date], 
       DailyFlash03.[fiscal wk], 
       DailyFlash03.[fiscal month #], 
       DailyFlash03.[fiscal month], 
       DailyFlash03.[fiscal qtr], 
       DailyFlash03.[fiscal year], 
       DailyFlash03.[status], 
       DailyFlash03.[demand units], 
       DailyFlash03.[demand cost $], 
       DailyFlash03.[demand $], 
       DailyFlash03.[advertised demand $], 
       DailyFlash03.[demand margin $], 
       DailyFlash03.[demand margin %], 
       DailyFlash03.[demand aur], 
       DailyFlash03.[demand auc], 
       DailyFlash03.[tax $], 
       DailyFlash03.[cancel units], 
       DailyFlash03.[cancel cost $], 
       DailyFlash03.[cancel $], 
       DailyFlash03.[advertised cancel $], 
       DailyFlash03.[cancel $] - DailyFlash03.[cancel cost $]   AS [Cancel Margin $], 
       IIF(DailyFlash03.[cancel $] > 0, ( DailyFlash03.[cancel $] - DailyFlash03.[cancel cost $] ) / DailyFlash03.[cancel $], 0) AS [Cancel Margin %], 
       DailyFlash03.[shipped units], 
       DailyFlash03.[shipped cost $], 
       DailyFlash03.[shipped $], 
       DailyFlash03.[advertised shipped $], 
       DailyFlash03.[shipped margin $], 
       DailyFlash03.[shipped margin %], 
       DailyFlash03.[shipped aur], 
       DailyFlash03.[shipped auc], 
       Sum(dailyexch.exch_units)  AS [Exchange Units], 
       Sum(dailyexch.[exch_cost$])   AS [Exchange Cost $], 
       Sum(dailyexch.[exch_net$])   AS [Exchange $], 
       Sum(dailyexch.[exch_gross$])  AS [Advertised Exchange $] 
FROM   dbo.vwDailyUpdSlct_DailyFlash_03 AS DailyFlash03
       LEFT JOIN dbo.mktbl_dailyexch AS dailyexch 
              ON ( DailyFlash03.[status] = dailyexch.[status] ) 
                 AND ( DailyFlash03.[date] = dailyexch.[exch_date] ) 
GROUP  BY DailyFlash03.[date], 
          DailyFlash03.[fiscal wk], 
          DailyFlash03.[fiscal month #], 
          DailyFlash03.[fiscal month], 
          DailyFlash03.[fiscal qtr], 
          DailyFlash03.[fiscal year], 
          DailyFlash03.[status], 
          DailyFlash03.[demand units], 
          DailyFlash03.[demand cost $], 
          DailyFlash03.[demand $], 
          DailyFlash03.[advertised demand $], 
          DailyFlash03.[demand margin $], 
          DailyFlash03.[demand margin %], 
          DailyFlash03.[demand aur], 
          DailyFlash03.[demand auc], 
          DailyFlash03.[tax $], 
          DailyFlash03.[cancel units], 
          DailyFlash03.[cancel cost $], 
          DailyFlash03.[cancel $], 
          DailyFlash03.[advertised cancel $], 
          DailyFlash03.[cancel $] - DailyFlash03.[cancel cost $], 
          IIF(DailyFlash03.[cancel $] > 0, ( DailyFlash03.[cancel $] - DailyFlash03.[cancel cost $] ) / DailyFlash03.[cancel $], 0), 
          DailyFlash03.[shipped units], 
          DailyFlash03.[shipped cost $], 
          DailyFlash03.[shipped $], 
          DailyFlash03.[advertised shipped $], 
          DailyFlash03.[shipped margin $], 
          DailyFlash03.[shipped margin %], 
          DailyFlash03.[shipped aur], 
          DailyFlash03.[shipped auc]; 
GO
