SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[VWSlct_OrderFlow_04]
as
SELECT OrderFlow03.[Order #], OrderFlow03.[Internet Order #], OrderFlow03.Channel, OrderFlow03.[Customer #], OrderFlow03.[Order Date], OrderFlow03.[Item Date], OrderFlow03.Status, OrderFlow03.[Event #], OrderFlow03.[Demand Units], OrderFlow03.[Demand Cost $], OrderFlow03.[Demand $], OrderFlow03.[Advertised Demand $], OrderFlow03.[Tax $], OrderFlow03.INV10, OrderFlow03.Line, OrderFlow03.[Ordered Fiscal Wk], OrderFlow03.[Ordered Fiscal Month #], OrderFlow03.[Ordered Fiscal Month], OrderFlow03.[Ordered Fiscal Qtr], OrderFlow03.[Ordered Fiscal Year], OrderFlow03.[Immediate Cancel Units], OrderFlow03.[Immediate Cancel Cost $], OrderFlow03.[Immediate Cancel $], OrderFlow03.[Advertised Immediate Cancel $], OrderFlow03.[Immediate Cancel Date], OrderFlow03.[Immediate Cancel Fiscal Wk], OrderFlow03.[Immediate Cancel Fiscal Month #], OrderFlow03.[Immediate Cancel Fiscal Month], OrderFlow03.[Immediate Cancel Fiscal Qtr], OrderFlow03.[Immediate Cancel Fiscal Year], OrderFlow03.[Cancel Date], OrderFlow03.[Cancel Units], OrderFlow03.[Cancel Cost $], OrderFlow03.[Cancel $], OrderFlow03.[Advertised Cancel $], OrderFlow03.[Cancel RsnCd], OrderFlow03.[Cancel Rsn], OrderFlow03.[Cancel Fiscal Wk], OrderFlow03.[Cancel Fiscal Month #], OrderFlow03.[Cancel Fiscal Month], OrderFlow03.[Cancel Fiscal Qtr], OrderFlow03.[Cancel Fiscal Year], OrderFlow03.[Ship Date], OrderFlow03.[Shipped Units], OrderFlow03.[Shipped Cost $], OrderFlow03.[Shipped $], OrderFlow03.[Advertised Shipped $], OrderFlow03.[Shipped Fiscal Wk], OrderFlow03.[Shipped Fiscal Month #], OrderFlow03.[Shipped Fiscal Month], OrderFlow03.[Shipped Fiscal Qtr], OrderFlow03.[Shipped Fiscal Year], DailyRtn.Rtn_Date AS [Return Date], DailyRtn.Rtn_Units AS [Return Units], DailyRtn.[Rtn_Cost$] AS [Return Cost $], DailyRtn.[Rtn_Net$] AS [Return $], DailyRtn.[Rtn_Gross$] AS [Advertised Return $], DailyRtn.Rtn_RsnCd AS [Return RsnCd], DailyRtn.Rtn_RsnDesc AS [Return Rsn], DailyRtn.Rtn_Fiscal_Wk AS [Return Fiscal Wk], DailyRtn.[Rtn_Fiscal_Month#] AS [Return Fiscal Month #], DailyRtn.Rtn_Fiscal_Month AS [Return Fiscal Month], DailyRtn.Rtn_Fiscal_Qtr AS [Return Fiscal Qtr], DailyRtn.Rtn_Fiscal_Year AS [Return Fiscal Year]
FROM VWSlct_OrderFlow_03 as OrderFlow03 LEFT JOIN dbo.MkTbl_DailyRtn as DailyRtn ON (OrderFlow03.Line = DailyRtn.DSeq) AND (OrderFlow03.INV10 = DailyRtn.INV10) AND (OrderFlow03.[Order #] = DailyRtn.[Order#]);
GO
