SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

create view [dbo].[VWSlct_OrderFlow_05]
as
SELECT OrderFlow04.[Order #], OrderFlow04.[Internet Order #], OrderFlow04.Channel, OrderFlow04.[Customer #], OrderFlow04.[Order Date], OrderFlow04.[Item Date], OrderFlow04.Status, OrderFlow04.[Event #], OrderFlow04.[Demand Units], OrderFlow04.[Demand Cost $], OrderFlow04.[Demand $], OrderFlow04.[Advertised Demand $], OrderFlow04.[Tax $], OrderFlow04.INV10, OrderFlow04.Line, OrderFlow04.[Ordered Fiscal Wk], OrderFlow04.[Ordered Fiscal Month #], OrderFlow04.[Ordered Fiscal Month], OrderFlow04.[Ordered Fiscal Qtr], OrderFlow04.[Ordered Fiscal Year], OrderFlow04.[Immediate Cancel Units], OrderFlow04.[Immediate Cancel Cost $], OrderFlow04.[Immediate Cancel $], OrderFlow04.[Advertised Immediate Cancel $], OrderFlow04.[Immediate Cancel Date], OrderFlow04.[Immediate Cancel Fiscal Wk], OrderFlow04.[Immediate Cancel Fiscal Month #], OrderFlow04.[Immediate Cancel Fiscal Month], OrderFlow04.[Immediate Cancel Fiscal Qtr], OrderFlow04.[Immediate Cancel Fiscal Year], OrderFlow04.[Cancel Date], OrderFlow04.[Cancel Units], OrderFlow04.[Cancel Cost $], OrderFlow04.[Cancel $], OrderFlow04.[Advertised Cancel $], OrderFlow04.[Cancel RsnCd], OrderFlow04.[Cancel Rsn], OrderFlow04.[Cancel Fiscal Wk], OrderFlow04.[Cancel Fiscal Month #], OrderFlow04.[Cancel Fiscal Month], OrderFlow04.[Cancel Fiscal Qtr], OrderFlow04.[Cancel Fiscal Year], OrderFlow04.[Ship Date], OrderFlow04.[Shipped Units], OrderFlow04.[Shipped Cost $], OrderFlow04.[Shipped $], OrderFlow04.[Advertised Shipped $], OrderFlow04.[Shipped Fiscal Wk], OrderFlow04.[Shipped Fiscal Month #], OrderFlow04.[Shipped Fiscal Month], OrderFlow04.[Shipped Fiscal Qtr], OrderFlow04.[Shipped Fiscal Year], OrderFlow04.[Return Date], OrderFlow04.[Return Units], OrderFlow04.[Return Cost $], OrderFlow04.[Return $], OrderFlow04.[Advertised Return $], OrderFlow04.[Return RsnCd], OrderFlow04.[Return Rsn], OrderFlow04.[Return Fiscal Wk], OrderFlow04.[Return Fiscal Month #], OrderFlow04.[Return Fiscal Month], OrderFlow04.[Return Fiscal Qtr], OrderFlow04.[Return Fiscal Year], DailyExch.Exch_Date AS [Exchange Date], DailyExch.Exch_Units AS [Exchange Units], DailyExch.[Exch_Cost$] AS [Exchange Cost $], DailyExch.[Exch_Net$] AS [Exchange $], DailyExch.[Exch_Gross$] AS [Advertised Exchange $], DailyExch.Exch_RsnCd AS [Exchange RsnCd], DailyExch.Exch_RsnDesc AS [Exchange Reason], DailyExch.Exch_Fiscal_Wk AS [Exchange Fiscal Wk], DailyExch.[Exch_Fiscal_Month#] AS [Exchange Fiscal Month #], DailyExch.Exch_Fiscal_Month AS [Exchange Fiscal Month], DailyExch.Exch_Fiscal_Qtr AS [Exchange Fiscal Qtr], DailyExch.Exch_Fiscal_Year AS [Exchange Fiscal Year]
FROM VWSlct_OrderFlow_04 as OrderFlow04  LEFT JOIN dbo.MkTbl_DailyExch as DailyExch  ON (OrderFlow04.Line = DailyExch.DSeq) AND (OrderFlow04.INV10 = DailyExch.INV10) AND (OrderFlow04.[Order #] = DailyExch.[Order#]);
GO
