SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


create view [dbo].[VWSlct_OrderFlow_02]
as
SELECT OrderFlow01.[Order #], OrderFlow01.[Internet Order #], OrderFlow01.Channel, OrderFlow01.[Customer #], OrderFlow01.[Order Date], OrderFlow01.[Item Date], OrderFlow01.[Event #], OrderFlow01.[Demand Units], OrderFlow01.[Demand Cost $], OrderFlow01.[Demand $], OrderFlow01.[Advertised Demand $], OrderFlow01.[Tax $], OrderFlow01.INV10, OrderFlow01.Line, OrderFlow01.[Ordered Fiscal Wk], OrderFlow01.[Ordered Fiscal Month #], OrderFlow01.[Ordered Fiscal Month], OrderFlow01.[Ordered Fiscal Qtr], OrderFlow01.[Ordered Fiscal Year], OrderFlow01.[Immediate Cancel Units], OrderFlow01.[Immediate Cancel Cost $], OrderFlow01.[Immediate Cancel $], OrderFlow01.[Advertised Immediate Cancel $], OrderFlow01.[Immediate Cancel Date], OrderFlow01.[Immediate Cancel Fiscal Wk], OrderFlow01.[Immediate Cancel Fiscal Month #], OrderFlow01.[Immediate Cancel Fiscal Month], OrderFlow01.[Immediate Cancel Fiscal Qtr], OrderFlow01.[Immediate Cancel Fiscal Year], DailyShip.Ship_Date AS [Ship Date], Sum(DailyShip.Ship_Units) AS [Shipped Units], Sum(DailyShip.[Ship_Cost$]) AS [Shipped Cost $], Sum(DailyShip.[Ship_Net$]) AS [Shipped $], Sum(DailyShip.[Ship_Gross$]) AS [Advertised Shipped $], DailyShip.Ship_Fiscal_Wk AS [Shipped Fiscal Wk], DailyShip.[Ship_Fiscal_Month#] AS [Shipped Fiscal Month #], DailyShip.Ship_Fiscal_Month AS [Shipped Fiscal Month], DailyShip.Ship_Fiscal_Qtr AS [Shipped Fiscal Qtr], DailyShip.Ship_Fiscal_Year AS [Shipped Fiscal Year]
FROM VWSlct_OrderFlow_01 as OrderFlow01 LEFT JOIN dbo.MkTbl_DailyShip as DailyShip ON (OrderFlow01.Line = DailyShip.DSeq) AND (OrderFlow01.INV10 = DailyShip.INV10) AND (OrderFlow01.[Order #] = DailyShip.[Order#])
GROUP BY OrderFlow01.[Order #], OrderFlow01.[Internet Order #], OrderFlow01.Channel, OrderFlow01.[Customer #], OrderFlow01.[Order Date], OrderFlow01.[Item Date], OrderFlow01.[Event #], OrderFlow01.[Demand Units], OrderFlow01.[Demand Cost $], OrderFlow01.[Demand $], OrderFlow01.[Advertised Demand $], OrderFlow01.[Tax $], OrderFlow01.INV10, OrderFlow01.Line, OrderFlow01.[Ordered Fiscal Wk], OrderFlow01.[Ordered Fiscal Month #], OrderFlow01.[Ordered Fiscal Month], OrderFlow01.[Ordered Fiscal Qtr], OrderFlow01.[Ordered Fiscal Year], OrderFlow01.[Immediate Cancel Units], OrderFlow01.[Immediate Cancel Cost $], OrderFlow01.[Immediate Cancel $], OrderFlow01.[Advertised Immediate Cancel $], OrderFlow01.[Immediate Cancel Date], OrderFlow01.[Immediate Cancel Fiscal Wk], OrderFlow01.[Immediate Cancel Fiscal Month #], OrderFlow01.[Immediate Cancel Fiscal Month], OrderFlow01.[Immediate Cancel Fiscal Qtr], OrderFlow01.[Immediate Cancel Fiscal Year], DailyShip.Ship_Date, DailyShip.Ship_Fiscal_Wk, DailyShip.[Ship_Fiscal_Month#], DailyShip.Ship_Fiscal_Month, DailyShip.Ship_Fiscal_Qtr, DailyShip.Ship_Fiscal_Year;
GO
