SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view  [dbo].[vwDailyUpdSlct_DailyFlash_09]
as
SELECT DailyFlash_08.[date], 
       DailyFlash_08.[fiscal week], 
       DailyFlash_08.[fiscal month #], 
       DailyFlash_08.[fiscal month], 
       DailyFlash_08.[fiscal qtr], 
       DailyFlash_08.[fiscal year], 
       Count(shippingrevenue.[order #]) AS [# Orders], 
       DailyFlash_08.[demand units], 
       DailyFlash_08.[demand cost $], 
       DailyFlash_08.[demand $], 
       DailyFlash_08.[advertised demand $], 
       DailyFlash_08.[demand margin $], 
       IIF(DailyFlash_08.[demand $] > 0, ( DailyFlash_08.[demand $] - DailyFlash_08.[demand cost $] ) / DailyFlash_08.[demand $], 0) AS [Demand Margin %], 
       IIF(DailyFlash_08.[demand units] > 0, DailyFlash_08.[demand $] / DailyFlash_08.[demand units], 0)  AS [Demand AUR], 
       IIF(DailyFlash_08.[demand units] > 0, DailyFlash_08.[demand cost $] / DailyFlash_08.[demand units], 0) AS [Demand AUC], 
       DailyFlash_08.[demand tax $], 
       Sum(shippingrevenue.[shipping revenue $]) AS [Demand Shipping Revenue $], 
       DailyFlash_08.[cancel units], 
       DailyFlash_08.[cancel cost $], 
       DailyFlash_08.[cancel $], 
       DailyFlash_08.[advertised cancel $], 
       DailyFlash_08.[cancel margin $], 
       IIF([cancel $] > 0, ( [cancel $] - [cancel cost $] ) / [cancel $], 0) AS [Cancel Margin %], 
       DailyFlash_08.[shipped units], 
       DailyFlash_08.[shipped cost $], 
       DailyFlash_08.[shipped $], 
       DailyFlash_08.[advertised shipped $], 
       DailyFlash_08.[shipped margin $], 
       IIF(DailyFlash_08.[shipped $] > 0, ( DailyFlash_08.[shipped $] - DailyFlash_08.[shipped cost $] ) / DailyFlash_08.[shipped $], 0) AS [Shipped Margin %], 
       IIF(DailyFlash_08.[shipped units] > 0, DailyFlash_08.[shipped $] / DailyFlash_08.[shipped units], 0) AS [Shipped AUR], 
       IIF(DailyFlash_08.[shipped units] > 0, DailyFlash_08.[shipped cost $] / DailyFlash_08.[shipped units], 0) AS [Shipped AUC], 
       DailyFlash_08.[shipped shipping revenue $], 
       DailyFlash_08.[returned units], 
       DailyFlash_08.[returned cost $], 
       DailyFlash_08.[returned $], 
       DailyFlash_08.[advertised returned $], 
       DailyFlash_08.[returned margin $] 
FROM   dbo.vwDailyUpdSlct_DailyFlash_08 AS DailyFlash_08
       LEFT JOIN dbo.slct_shippingrevenue AS shippingrevenue 
              ON DailyFlash_08.[date] = shippingrevenue.[first order date] 
GROUP  BY DailyFlash_08.[date], 
          DailyFlash_08.[fiscal week], 
          DailyFlash_08.[fiscal month #], 
          DailyFlash_08.[fiscal month], 
          DailyFlash_08.[fiscal qtr], 
          DailyFlash_08.[fiscal year], 
          DailyFlash_08.[demand units], 
          DailyFlash_08.[demand cost $], 
          DailyFlash_08.[demand $], 
          DailyFlash_08.[advertised demand $], 
          DailyFlash_08.[demand margin $], 
          IIF(DailyFlash_08.[demand $] > 0, ( DailyFlash_08.[demand $] - DailyFlash_08.[demand cost $] ) / DailyFlash_08.[demand $], 0), 
          IIF(DailyFlash_08.[demand units] > 0, DailyFlash_08.[demand $] / DailyFlash_08.[demand units], 0), 
          IIF(DailyFlash_08.[demand units] > 0, DailyFlash_08.[demand cost $] / DailyFlash_08.[demand units], 0), 
          DailyFlash_08.[demand tax $], 
          DailyFlash_08.[cancel units], 
          DailyFlash_08.[cancel cost $], 
          DailyFlash_08.[cancel $], 
          DailyFlash_08.[advertised cancel $], 
          DailyFlash_08.[cancel margin $], 
          IIF(DailyFlash_08.[cancel $] > 0, ( DailyFlash_08.[cancel $] - DailyFlash_08.[cancel cost $] ) / DailyFlash_08.[cancel $], 0), 
          DailyFlash_08.[shipped units], 
          DailyFlash_08.[shipped cost $], 
          DailyFlash_08.[shipped $], 
          DailyFlash_08.[advertised shipped $], 
          DailyFlash_08.[shipped margin $], 
          IIF(DailyFlash_08.[shipped $] > 0, ( DailyFlash_08.[shipped $] - DailyFlash_08.[shipped cost $] ) / DailyFlash_08.[shipped $], 0), 
          IIF(DailyFlash_08.[shipped units] > 0, DailyFlash_08.[shipped $] / DailyFlash_08.[shipped units], 0), 
          IIF(DailyFlash_08.[shipped units] > 0, DailyFlash_08.[shipped cost $] / DailyFlash_08.[shipped units], 0), 
          DailyFlash_08.[shipped shipping revenue $], 
          DailyFlash_08.[returned units], 
          DailyFlash_08.[returned cost $], 
          DailyFlash_08.[returned $], 
          DailyFlash_08.[advertised returned $], 
          DailyFlash_08.[returned margin $]; 
GO
