SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/*
*   SSMA warning messages:
*   A2SS0030: View 'Find duplicates for LinkTbl_Ord_Dtl' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW [dbo].[Find duplicates for LinkTbl_Ord_Dtl]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 8.1.0.*/
   SELECT TOP 9223372036854775807 WITH TIES 
      [LinkTbl_Ord_Dtl].[Cat], 
      [LinkTbl_Ord_Dtl].[Source Cd], 
      [LinkTbl_Ord_Dtl].[Invid], 
      [LinkTbl_Ord_Dtl].[ORDDTL], 
      [LinkTbl_Ord_Dtl].[SGORDNO], 
      [LinkTbl_Ord_Dtl].[Itemdt], 
      [LinkTbl_Ord_Dtl].[Ordrd], 
      [LinkTbl_Ord_Dtl].[Net Price], 
      [LinkTbl_Ord_Dtl].[Gpricedd], 
      [LinkTbl_Ord_Dtl].[INVCOSTDD], 
      [LinkTbl_Ord_Dtl].[Taxdd], 
      [LinkTbl_Ord_Dtl].[Shiphanddd], 
      [LinkTbl_Ord_Dtl].[Base#], 
      [LinkTbl_Ord_Dtl].[LONGDESCTX], 
      [LinkTbl_Ord_Dtl].[Inet Ord ID], 
      [LinkTbl_Ord_Dtl].[POS]
   FROM [LinkTbl_Ord_Dtl]
   WHERE ((([LinkTbl_Ord_Dtl].[Cat]) IN 
      (
         SELECT [Cat]
         FROM [LinkTbl_Ord_Dtl]  AS Tmp
         GROUP BY [Cat], [Source Cd], [ORDDTL], [Invid]
         HAVING 
            Count(*) > 1 AND 
            [Source Cd] = [LinkTbl_Ord_Dtl].[Source Cd] AND 
            [ORDDTL] = [LinkTbl_Ord_Dtl].[ORDDTL] AND 
            [Invid] = [LinkTbl_Ord_Dtl].[Invid]
      )))
   ORDER BY 
      [LinkTbl_Ord_Dtl].[Cat], 
      [LinkTbl_Ord_Dtl].[Source Cd], 
      [LinkTbl_Ord_Dtl].[Invid], 
      [LinkTbl_Ord_Dtl].[ORDDTL]
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Access Tbls 2.[Find duplicates for LinkTbl_Ord_Dtl]', 'SCHEMA', N'dbo', 'VIEW', N'Find duplicates for LinkTbl_Ord_Dtl', NULL, NULL
GO
