SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE  PROCEDURE [dbo].[SpMkTbl_OrderFlow_bkp_1108]

as
BEGIN
	BEGIN
	IF  EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'MkTbl_OrderFlow') 
    AND type = N'U')
	DROP TABLE MkTbl_OrderFlow

SELECT   VWSlct_OrderFlow_06.[category], 
       VWSlct_OrderFlow_06.[division], 
       VWSlct_OrderFlow_06.[department], 
       VWSlct_OrderFlow_06.[class], 
       VWSlct_OrderFlow_06.[style], 
       VWSlct_OrderFlow_06.[color], 
       VWSlct_OrderFlow_06.[size], 
       VWSlct_OrderFlow_06.[inv5], 
       VWSlct_OrderFlow_06.[inv7], 
       VWSlct_OrderFlow_06.[inv10], 
       VWSlct_OrderFlow_06.[vendor #], 
       VWSlct_OrderFlow_06.[vendor], 
       VWSlct_OrderFlow_06.[vendor style], 
       VWSlct_OrderFlow_06.[original price], 
       VWSlct_OrderFlow_06.[current price], 
       VWSlct_OrderFlow_06.[current cost], 
       VWSlct_OrderFlow_06.[current event #], 
       VWSlct_OrderFlow_06.[current event], 
       VWSlct_OrderFlow_06.[last event #], 
       VWSlct_OrderFlow_06.[last event], 
       VWSlct_OrderFlow_06.[first sales date], 
       VWSlct_OrderFlow_06.[first receipt date], 
       VWSlct_OrderFlow_06.[last receipt date], 
       VWSlct_OrderFlow_06.[next receipt date], 
       VWSlct_OrderFlow_06.[current oh units], 
       VWSlct_OrderFlow_06.[current oo units], 
       VWSlct_OrderFlow_06.[next 30 days oo units], 
       VWSlct_OrderFlow_06.[current backorder units], 
       VWSlct_OrderFlow_06.[current backorder cost $], 
       VWSlct_OrderFlow_06.[current backorder $], 
       VWSlct_OrderFlow_06.[return %], 
       VWSlct_OrderFlow_06.[order #], 
       VWSlct_OrderFlow_06.[internet order #], 
       VWSlct_OrderFlow_06.[line], 
       VWSlct_OrderFlow_06.[channel], 
       VWSlct_OrderFlow_06.[customer #], 
       VWSlct_OrderFlow_06.[order date], 
       VWSlct_OrderFlow_06.[item date], 
       VWSlct_OrderFlow_06.[status], 
       VWSlct_OrderFlow_06.[event #], 
       reftbl_catalog.[description] AS [Event], 
       VWSlct_OrderFlow_06.[demand units], 
       VWSlct_OrderFlow_06.[demand cost $], 
       VWSlct_OrderFlow_06.[demand $], 
       VWSlct_OrderFlow_06.[advertised demand $], 
       VWSlct_OrderFlow_06.[tax $], 
       VWSlct_OrderFlow_06.[ordered fiscal wk], 
       VWSlct_OrderFlow_06.[ordered fiscal month #], 
       VWSlct_OrderFlow_06.[ordered fiscal month], 
       VWSlct_OrderFlow_06.[ordered fiscal qtr], 
       VWSlct_OrderFlow_06.[ordered fiscal year], 
       VWSlct_OrderFlow_06.[immediate cancel units], 
       VWSlct_OrderFlow_06.[immediate cancel cost $], 
       VWSlct_OrderFlow_06.[immediate cancel $], 
       VWSlct_OrderFlow_06.[advertised immediate cancel $], 
       VWSlct_OrderFlow_06.[immediate cancel date], 
       VWSlct_OrderFlow_06.[immediate cancel fiscal wk], 
       VWSlct_OrderFlow_06.[immediate cancel fiscal month #], 
       VWSlct_OrderFlow_06.[immediate cancel fiscal month], 
       VWSlct_OrderFlow_06.[immediate cancel fiscal qtr], 
       VWSlct_OrderFlow_06.[immediate cancel fiscal year], 
       VWSlct_OrderFlow_06.[cancel date], 
       VWSlct_OrderFlow_06.[cancel units], 
       VWSlct_OrderFlow_06.[cancel cost $], 
       VWSlct_OrderFlow_06.[cancel $], 
       VWSlct_OrderFlow_06.[advertised cancel $], 
       VWSlct_OrderFlow_06.[cancel rsncd], 
       VWSlct_OrderFlow_06.[cancel rsn], 
       VWSlct_OrderFlow_06.[cancel fiscal wk], 
       VWSlct_OrderFlow_06.[cancel fiscal month #], 
       VWSlct_OrderFlow_06.[cancel fiscal month], 
       VWSlct_OrderFlow_06.[cancel fiscal qtr], 
       VWSlct_OrderFlow_06.[cancel fiscal year], 
       VWSlct_OrderFlow_06.[ship date], 
       VWSlct_OrderFlow_06.[shipped units], 
       VWSlct_OrderFlow_06.[shipped cost $], 
       VWSlct_OrderFlow_06.[shipped $], 
       VWSlct_OrderFlow_06.[advertised shipped $], 
       VWSlct_OrderFlow_06.[shipped fiscal wk], 
       VWSlct_OrderFlow_06.[shipped fiscal month #], 
       VWSlct_OrderFlow_06.[shipped fiscal month], 
       VWSlct_OrderFlow_06.[shipped fiscal qtr], 
       VWSlct_OrderFlow_06.[shipped fiscal year], 
       VWSlct_OrderFlow_06.[return date], 
       VWSlct_OrderFlow_06.[return units], 
       VWSlct_OrderFlow_06.[return cost $], 
       VWSlct_OrderFlow_06.[return $], 
       VWSlct_OrderFlow_06.[advertised return $], 
       VWSlct_OrderFlow_06.[return rsncd], 
       VWSlct_OrderFlow_06.[return rsn], 
       VWSlct_OrderFlow_06.[return fiscal wk], 
       VWSlct_OrderFlow_06.[return fiscal month #], 
       VWSlct_OrderFlow_06.[return fiscal month], 
       VWSlct_OrderFlow_06.[return fiscal qtr], 
       VWSlct_OrderFlow_06.[return fiscal year], 
       VWSlct_OrderFlow_06.[exchange date], 
       VWSlct_OrderFlow_06.[exchange units], 
       VWSlct_OrderFlow_06.[exchange cost $], 
       VWSlct_OrderFlow_06.[exchange $], 
       VWSlct_OrderFlow_06.[advertised exchange $], 
       VWSlct_OrderFlow_06.[exchange rsncd], 
       VWSlct_OrderFlow_06.[exchange reason], 
       VWSlct_OrderFlow_06.[exchange fiscal wk], 
       VWSlct_OrderFlow_06.[exchange fiscal month #], 
       VWSlct_OrderFlow_06.[exchange fiscal month], 
       VWSlct_OrderFlow_06.[exchange fiscal qtr], 
       VWSlct_OrderFlow_06.[exchange fiscal year] 
INTO   MkTbl_OrderFlow 
FROM   VWslct_orderflow_06 
       LEFT JOIN RefTbl_Catalog 
              ON VWslct_orderflow_06.[event #] = RefTbl_Catalog.[offer_id]

			  END
			  END
GO
