CREATE TABLE [dbo].[F21_VDRS_ORDER_DETAIL]
(
[COMPANY_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIVISION_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDER_NO] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ORDER_LINE] [float] NOT NULL,
[OFFER_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OFFER_YEAR] [float] NULL,
[KEY_CODE] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDER_DATE] [datetime] NULL,
[ORIG_DIVISION_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIG_OFFER_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALENDAR_SEQ] [float] NULL,
[PRODUCT_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIG_OFFER_YEAR] [float] NULL,
[DESCRIPTOR1] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTOR2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTOR3] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEMAND_FROM] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEMAND_TYPE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_SOLD] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_SHIP] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUANTITY] [float] NULL,
[EXT_PRICE] [float] NULL,
[EXT_COST] [float] NULL,
[CURRENT_STATUS] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BO_DATE] [datetime] NULL,
[CANCEL_DATE] [datetime] NULL,
[SHIP_DATE] [datetime] NULL,
[CREATED_DATETIME] [datetime] NULL,
[LAST_UPDATED_DATETIME] [datetime] NULL,
[LAST_UPDATED_BY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SH_COST] [float] NULL,
[SH_REVENUE] [float] NULL,
[SHIP_METHOD] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_METHOD] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CANCEL_QUANTITY] [float] NULL,
[SHIP_QUANTITY] [float] NULL,
[TOTAL_CREDIT] [float] NULL,
[SALESPERSON] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIST_PRICE] [float] NULL,
[SHIP_REFERENCE_NO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBSTITUTED_SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_DECISION] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_SITE] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_PAYER] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FUTURE_SHIP_DATE] [datetime] NULL,
[UNUSUAL_DEMAND_STATUS] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALTERNATE_KEY_CODE] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_DATE] [datetime] NULL,
[RETURN_QUANTITY] [float] NULL,
[RESELLABLE_QUANTITY] [float] NULL,
[RETURN_CODE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_ACTION] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_SH_COST] [float] NULL,
[RETURN_SH_REVENUE] [float] NULL,
[ALTERNATE_TRACKING_ID] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALTERNATE_TRACKING_ORDER_LINE] [float] NULL,
[SALES_TAX_REFUND] [float] NULL,
[RESTOCK_CHARGE] [float] NULL,
[RETURN_SALESPERSON] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_TOTAL_CREDIT] [float] NULL,
[SKU_STATUS] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COST_EA] [float] NULL,
[STD_PRICE_EA] [float] NULL,
[STD_COST_EA] [float] NULL,
[SUB_CATEGORY_ID] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEGORY_ID] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT_VENDOR_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUYER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHEDULER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCT_ENGINEER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DROP_SHIP_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_CODE] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDOR_NAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEGORY_DESC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBCATEGORY_DESC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU_DESCRIPTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCT_DESCRIPTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WAREHOUSE_DEMAND] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WAREHOUSE_SHIPPED] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrOn] [datetime] NULL CONSTRAINT [DF_F21_VDRS_ORDER_DETAIL_CrOn] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[F21_VDRS_ORDER_DETAIL] ADD CONSTRAINT [F21_VDRS_ORDER_DETAIL$PrimaryKey] PRIMARY KEY CLUSTERED  ([ORDER_NO], [ORDER_LINE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [LastUpdOn] ON [dbo].[F21_VDRS_ORDER_DETAIL] ([LAST_UPDATED_DATETIME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [OrderDate] ON [dbo].[F21_VDRS_ORDER_DETAIL] ([ORDER_DATE]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ALTERNATE_KEY_CODE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ALTERNATE_KEY_CODE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ALTERNATE_TRACKING_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ALTERNATE_TRACKING_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ALTERNATE_TRACKING_ORDER_LINE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ALTERNATE_TRACKING_ORDER_LINE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[BO_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'BO_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[BUYER]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'BUYER'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CALENDAR_SEQ]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CALENDAR_SEQ'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CANCEL_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CANCEL_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CANCEL_QUANTITY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CANCEL_QUANTITY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CATEGORY_DESC]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CATEGORY_DESC'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CATEGORY_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CATEGORY_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CLASS_CODE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CLASS_CODE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[COMPANY_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'COMPANY_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[COST_EA]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'COST_EA'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CREATED_DATETIME]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CREATED_DATETIME'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CURRENT_STATUS]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CURRENT_STATUS'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CUSTOMER_DECISION]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CUSTOMER_DECISION'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CUSTOMER_PAYER]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CUSTOMER_PAYER'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CUSTOMER_SHIP]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CUSTOMER_SHIP'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CUSTOMER_SITE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CUSTOMER_SITE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[CUSTOMER_SOLD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'CUSTOMER_SOLD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DEFAULT_VENDOR_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DEFAULT_VENDOR_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DEMAND_FROM]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DEMAND_FROM'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DEMAND_TYPE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DEMAND_TYPE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DESCRIPTOR1]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DESCRIPTOR1'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DESCRIPTOR2]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DESCRIPTOR2'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DESCRIPTOR3]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DESCRIPTOR3'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DIVISION_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DIVISION_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[DROP_SHIP_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'DROP_SHIP_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[EXT_COST]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'EXT_COST'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[EXT_PRICE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'EXT_PRICE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[FUTURE_SHIP_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'FUTURE_SHIP_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[KEY_CODE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'KEY_CODE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[LAST_UPDATED_BY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'LAST_UPDATED_BY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[LAST_UPDATED_DATETIME]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'LAST_UPDATED_DATETIME'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[LIST_PRICE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'LIST_PRICE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[OFFER_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'OFFER_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[OFFER_YEAR]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'OFFER_YEAR'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ORDER_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ORDER_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ORDER_LINE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ORDER_LINE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ORDER_NO]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ORDER_NO'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ORIG_DIVISION_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ORIG_DIVISION_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ORIG_OFFER_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ORIG_OFFER_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[ORIG_OFFER_YEAR]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'ORIG_OFFER_YEAR'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[PAY_METHOD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'PAY_METHOD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[PRODUCT_DESCRIPTION]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'PRODUCT_DESCRIPTION'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[PRODUCT_ENGINEER]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'PRODUCT_ENGINEER'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[PRODUCT_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'PRODUCT_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[QUANTITY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'QUANTITY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RESELLABLE_QUANTITY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RESELLABLE_QUANTITY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RESTOCK_CHARGE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RESTOCK_CHARGE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_ACTION]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_ACTION'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_CODE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_CODE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_QUANTITY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_QUANTITY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_SALESPERSON]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_SALESPERSON'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_SH_COST]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_SH_COST'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_SH_REVENUE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_SH_REVENUE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[RETURN_TOTAL_CREDIT]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'RETURN_TOTAL_CREDIT'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SALES_TAX_REFUND]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SALES_TAX_REFUND'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SALESPERSON]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SALESPERSON'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SCHEDULER]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SCHEDULER'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SH_COST]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SH_COST'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SH_REVENUE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SH_REVENUE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SHIP_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SHIP_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SHIP_METHOD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SHIP_METHOD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SHIP_QUANTITY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SHIP_QUANTITY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SHIP_REFERENCE_NO]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SHIP_REFERENCE_NO'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SKU]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SKU'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SKU_DESCRIPTION]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SKU_DESCRIPTION'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SKU_STATUS]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SKU_STATUS'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[STD_COST_EA]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'STD_COST_EA'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[STD_PRICE_EA]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'STD_PRICE_EA'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SUB_CATEGORY_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SUB_CATEGORY_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SUBCATEGORY_DESC]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SUBCATEGORY_DESC'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[SUBSTITUTED_SKU]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'SUBSTITUTED_SKU'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[TOTAL_CREDIT]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'TOTAL_CREDIT'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[UNUSUAL_DEMAND_STATUS]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'UNUSUAL_DEMAND_STATUS'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER1]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER1'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER2]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER2'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER3]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER3'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER4]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER4'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER5]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER5'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER6]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER6'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER7]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER7'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[USER8]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'USER8'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[VENDOR_NAME]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'VENDOR_NAME'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[WAREHOUSE_DEMAND]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'WAREHOUSE_DEMAND'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[WAREHOUSE_SHIPPED]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'COLUMN', N'WAREHOUSE_SHIPPED'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'Tables Only.[testTbl_F21_VDRS_ORDER_DETAIL].[PrimaryKey]', 'SCHEMA', N'dbo', 'TABLE', N'F21_VDRS_ORDER_DETAIL', 'CONSTRAINT', N'F21_VDRS_ORDER_DETAIL$PrimaryKey'
GO
