CREATE TABLE [dbo].[PBI_Backorder_0810_1]
(
[category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Price] [money] NULL,
[Current Price] [money] NULL,
[Current Cost] [money] NULL,
[Current OH Units] [float] NULL,
[Current OO Units] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next 30 Days OO Units] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Event #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Event] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Event #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Event] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Sales Date] [datetime] NULL,
[First Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next Receipt Date] [datetime] NULL,
[2nd Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3rd Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[4th Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[5th Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Return %] [float] NULL,
[Item Date] [datetime] NULL,
[Ordered Fiscal Wk] [float] NULL,
[Ordered Fiscal Month #] [float] NULL,
[Ordered Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ordered Fiscal Qtr] [float] NULL,
[Ordered Fiscal Year] [float] NULL,
[Order #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Open Demand Units] [float] NULL,
[Open Demand Cost $] [money] NULL,
[Open Demand $] [money] NULL,
[Open Advertised Demand $] [money] NULL,
[Backorder Units] [float] NULL,
[Backorder Cost $] [money] NULL,
[Backorder $] [money] NULL,
[Backorder Margin $] [money] NULL,
[Expected Fill Units] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expected Fill $] [money] NULL,
[Expected Fill Margin $] [money] NULL,
[Expected Fill NDC Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expected Fill Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expected Fill Fiscal Wk] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expected Fill Fiscal Month #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expected Fill Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expected Fill Fiscal Qtr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expected Fill Fiscal Year] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
