CREATE TABLE [dbo].[MkTbl_OrderFlow_Import3007]
(
[Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor Style] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Price] [float] NULL,
[Current Price] [float] NULL,
[Current Cost] [float] NULL,
[Current Event #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Event] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Event #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Event] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Sales Date] [datetime] NULL,
[First Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next Receipt Date] [datetime] NULL,
[Current OH Units] [float] NULL,
[Current OO Units] [float] NULL,
[Next 30 Days OO Units] [float] NULL,
[Current Backorder Units] [float] NULL,
[Current Backorder Cost $] [float] NULL,
[Current Backorder $] [float] NULL,
[Return %] [float] NULL,
[Order #] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Internet Order #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Line] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Channel] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer #] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Date] [datetime] NULL,
[Item Date] [datetime] NULL,
[Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Event #] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Event] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Demand Units] [float] NULL,
[Demand Cost $] [float] NULL,
[Demand $] [float] NULL,
[Advertised Demand $] [float] NULL,
[Tax $] [float] NULL,
[Ordered Fiscal Wk] [float] NULL,
[Ordered Fiscal Month #] [float] NULL,
[Ordered Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ordered Fiscal Qtr] [float] NULL,
[Ordered Fiscal Year] [float] NULL,
[Immediate Cancel Units] [float] NULL,
[Immediate Cancel Cost $] [float] NULL,
[Immediate Cancel $] [float] NULL,
[Advertised Immediate Cancel $] [float] NULL,
[Immediate Cancel Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Immediate Cancel Fiscal Wk] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Immediate Cancel Fiscal Month #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Immediate Cancel Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Immediate Cancel Fiscal Qtr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Immediate Cancel Fiscal Year] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel Date] [datetime] NULL,
[Cancel Units] [float] NULL,
[Cancel Cost $] [float] NULL,
[Cancel $] [float] NULL,
[Advertised Cancel $] [float] NULL,
[Cancel RsnCd] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel Rsn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel Fiscal Wk] [float] NULL,
[Cancel Fiscal Month #] [float] NULL,
[Cancel Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel Fiscal Qtr] [float] NULL,
[Cancel Fiscal Year] [float] NULL,
[Ship Date] [datetime] NULL,
[Shipped Units] [float] NULL,
[Shipped Cost $] [float] NULL,
[Shipped $] [float] NULL,
[Advertised Shipped $] [float] NULL,
[Shipped Fiscal Wk] [float] NULL,
[Shipped Fiscal Month #] [float] NULL,
[Shipped Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipped Fiscal Qtr] [float] NULL,
[Shipped Fiscal Year] [float] NULL,
[Return Date] [datetime] NULL,
[Return Units] [float] NULL,
[Return Cost $] [float] NULL,
[Return $] [float] NULL,
[Advertised Return $] [float] NULL,
[Return RsnCd] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Return Rsn] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Return Fiscal Wk] [float] NULL,
[Return Fiscal Month #] [float] NULL,
[Return Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Return Fiscal Qtr] [float] NULL,
[Return Fiscal Year] [float] NULL,
[Exchange Date] [datetime] NULL,
[Exchange Units] [float] NULL,
[Exchange Cost $] [float] NULL,
[Exchange $] [float] NULL,
[Advertised Exchange $] [float] NULL,
[Exchange RsnCd] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exchange Reason] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exchange Fiscal Wk] [float] NULL,
[Exchange Fiscal Month #] [float] NULL,
[Exchange Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exchange Fiscal Qtr] [float] NULL,
[Exchange Fiscal Year] [float] NULL
) ON [PRIMARY]
GO
