CREATE TABLE [dbo].[F21.FMSH_STOCK_ON_HANDtest]
(
[COMPANY_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MS_VERSION_NO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WAREHOUSE_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV_EXPIRATION_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATED_DATETIME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_UPDATED_DATETIME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_UPDATED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
