CREATE TABLE [dbo].[F21_FMSH_WEEKLY_INVENTORY_POSITION2]
(
[COMPANY_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WAREHOUSE_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CALENDAR_SEQ] [float] NOT NULL,
[STATUS_ID] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UNITS] [float] NULL,
[COST_EA] [float] NULL,
[STD_COST_EA] [float] NULL,
[INVENTORY_VARIANCE_EA] [float] NULL,
[ADDITIONAL_COST_EA] [float] NULL,
[AGENT_FEES_EA] [float] NULL,
[DUTY_FEES_EA] [float] NULL,
[FREIGHT_FEES_EA] [float] NULL,
[PRICE_EA] [float] NULL,
[OUT_OF_STOCK_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEG_UNITS] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[F21_FMSH_WEEKLY_INVENTORY_POSITION2] ADD CONSTRAINT [F21_FMSH_WEEKLY_INVENTORY_POSITION2_PK] PRIMARY KEY CLUSTERED  ([COMPANY_ID], [SKU], [WAREHOUSE_ID], [CALENDAR_SEQ], [STATUS_ID]) ON [PRIMARY]
GO
