CREATE TABLE [dbo].[F21_FADM_FISCAL_CALENDAR2]
(
[COMPANY_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CALENDAR_SEQ] [float] NOT NULL,
[FISCAL_YEAR] [float] NOT NULL,
[FISCAL_WEEK] [float] NULL,
[WEEK_BEGIN_DATE] [datetime] NULL,
[WEEK_END_DATE] [datetime] NULL,
[PERIOD_GROUP] [float] NOT NULL,
[CREATED_DATETIME] [datetime] NULL,
[WEEK_DESCRIPTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_UPDATED_DATETIME] [datetime2] (0) NULL,
[LAST_UPDATED_BY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MASTERSCHEDULING_NOTES] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FISCAL_MONTH] [float] NULL,
[FISCAL_QUARTER] [float] NULL,
[HIST_CALENDAR_SEQ] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[F21_FADM_FISCAL_CALENDAR2] ADD CONSTRAINT [PK_F21_FADM_FISCAL_CALENDAR2] PRIMARY KEY CLUSTERED  ([COMPANY_ID], [CALENDAR_SEQ], [FISCAL_YEAR], [PERIOD_GROUP]) ON [PRIMARY]
GO
