CREATE TABLE [dbo].[MkTbl_Hindsight_2907]
(
[HandsightCtr] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Return Rate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor Style #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond Basic] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Future Event] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Price] [float] NULL,
[Current Price] [float] NULL,
[Current Discount %] [float] NULL,
[Cost] [float] NULL,
[OH Units] [float] NULL,
[OO Units] [float] NULL,
[Event OO Units] [float] NULL,
[Requested OO Units] [float] NULL,
[Backorder Units] [float] NULL,
[Event BOP U] [float] NULL,
[Event Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Event #] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Event Go Live] [datetime] NULL,
[Current Event #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual Demand Units] [float] NULL,
[Actual Demand Cost $] [float] NULL,
[Actual Demand $] [float] NULL,
[Actual Gross Demand $] [float] NULL,
[Actual Offered Demand $] [float] NULL,
[Projection Offered Demand $] [float] NULL,
[Projection Ticket Demand $] [float] NULL,
[Projection Demand Cost $] [float] NULL,
[Projection Demand Units] [float] NULL,
[1st Projection Offered Demand $] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1st Projection Demand Cost $] [float] NULL,
[1st Projection Demand Units] [float] NULL,
[Plan Offered Demand $] [float] NULL,
[Plan Gross Demand $] [float] NULL,
[Plan Net Demand $] [float] NULL,
[Plan Demand Cost $] [float] NULL,
[Plan Demand Units] [float] NULL,
[Forecast Offered Demand $] [float] NULL,
[Forecast Gross Demand $] [float] NULL,
[Forecast Net Demand $] [float] NULL,
[Forecast Demand Cost $] [float] NULL,
[Forecast Demand Units] [float] NULL,
[Spring Trans 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 1 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 2 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 1 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 2 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 3 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall Trans 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 1 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 2 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Holiday 18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring Trans 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 1 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 2 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 1 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 2 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 3 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vacation 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 1 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 2 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Holiday 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring Trans 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 1 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 2 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 1 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 2 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 3 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 1 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 2 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Holiday 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring Trans 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 1 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spring 2 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 1 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 2 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Summer 3 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 1 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fall 2 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Winter 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Holiday 21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond Basics Spring 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond Basics Fall 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond Basics Spring 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond Basics Summer 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond Basics Fall 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Beyond Basics Winter 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Ex Spring 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Ex Fall 19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Ex Spring 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Ex Summer 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Ex Fall 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Web Ex Winter 20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
