CREATE TABLE [dbo].[MkTbl_Backorders]
(
[Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INV10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Original Price] [float] NULL,
[Current Price] [float] NULL,
[Current Cost] [float] NULL,
[Current OH Units] [float] NULL,
[Current OO Units] [float] NULL,
[Next 30 Days OO Units] [float] NULL,
[Current Event #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Event] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Event #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Event] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Sales Date] [datetime] NULL,
[First Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Receipt Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next Receipt Date] [datetime] NULL,
[Return %] [float] NULL,
[Item Date] [datetime] NULL,
[Order #] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Open Demand Units] [float] NULL,
[Open Demand Cost $] [float] NULL,
[Open Demand $] [float] NULL,
[Open Advertised Demand $] [float] NULL,
[Ordered Fiscal Wk] [float] NULL,
[Ordered Fiscal Month #] [float] NULL,
[Ordered Fiscal Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ordered Fiscal Qtr] [float] NULL,
[Ordered Fiscal Year] [float] NULL
) ON [PRIMARY]
GO
